### 게시글 생성
POST http://localhost:8080/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QHRlc3QuY29tIiwiaWF0IjoxNzg5Mzg2MjUxLCJleHAiOjE3ODkzODk4NTF9.FUfzy2DUux-EcggDIXBC6WyIAJACWd3jK8aG5GGrEnwWhAIByPT3XM1TjXJZbVM6

{
  "title": "첫 글",
  "content": "헥사고날 연습중"
}

### 단건 조회
GET http://localhost:8080/api/posts/6aa4ff322d70adeed3bc4015
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QHRlc3QuY29tIiwiaWF0IjoxNzg5Mzg2MjUxLCJleHAiOjE3ODkzODk4NTF9.FUfzy2DUux-EcggDIXBC6WyIAJACWd3jK8aG5GGrEnwWhAIByPT3XM1TjXJZbVM6

### 목록 조회
GET http://localhost:8080/api/posts
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QHRlc3QuY29tIiwiaWF0IjoxNzg5Mzg2MjUxLCJleHAiOjE3ODkzODk4NTF9.FUfzy2DUux-EcggDIXBC6WyIAJACWd3jK8aG5GGrEnwWhAIByPT3XM1TjXJZbVM6

### 제목 검색
GET http://localhost:8080/api/posts/search?keyword=첫
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QHRlc3QuY29tIiwiaWF0IjoxNzg5Mzg2MjUxLCJleHAiOjE3ODkzODk4NTF9.FUfzy2DUux-EcggDIXBC6WyIAJACWd3jK8aG5GGrEnwWhAIByPT3XM1TjXJZbVM6

### 존재하지 않는 게시글 조회 (404 나와야 정상)
GET http://localhost:8080/api/posts/9999

### 회원가입
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password123"
}

### 로그인 (응답의 accessToken 값을 복사해서 아래 4번 요청에 사용)
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password123"
}

### 토큰 없이 게시글 목록 조회 (401 떠야 정상)
GET http://localhost:8080/api/posts

### 토큰 넣고 게시글 목록 조회 (200 떠야 정상 - Bearer 뒤에 2번 응답의 accessToken 붙여넣기)
GET http://localhost:8080/api/posts
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QHRlc3QuY29tIiwiaWF0IjoxNzg5MTk3NDk3LCJleHAiOjE3ODkyMDEwOTd9.ehBs_4Z4R6qtvVc4bIb3SIiE4SjPkAFi-Ugl9_dbyea9Jtj7Pf8COYLXlyhdlaYo